const items = [
  {
    id: "001",
    image: "../Images/productImages/image1.jpg",
    company: "SASSAFRAS",
    item_name: "Women High-Rise Trousers",
    original_price: 1699,
    current_price: 713,
    discount_percentage: 58,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.2,
      count: "18k",
    },
  },
  {
    id: "002",
    image: "../Images/productImages/image2.jpg",
    company: "SASSAFRAS",
    item_name: "Floral Waist Cut-Out Dress",
    original_price: 2498,
    current_price: 1099,
    discount_percentage: 56,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.4,
      count: "22.1k",
    },
  },
  {
    id: "003",
    image: "../Images/productImages/image3.jpg",
    company: "Tokyo Talkies",
    item_name: "Shoulder Straps Maxi Dress",
    original_price: 2199,
    current_price: 659,
    discount_percentage: 70,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.2,
      count: "3.9k",
    },
  },
  {
    id: "004",
    image: "../Images/productImages/image4.jpg",
    company: "Trendyol",
    item_name: "V-Neck Woven Waistcoat",
    original_price: 2799,
    current_price: 1539,
    discount_percentage: 45,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.3,
      count: "319",
    },
  },
  {
    id: "005",
    image: "../Images/productImages/image5.jpg",
    company: "Bannos Swagger",
    item_name: "Applique Detail Night Suit",
    original_price: 4199,
    current_price: 755,
    discount_percentage: 82,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.1,
      count: "2.6k",
    },
  },
  {
    id: "006",
    image: "../Images/productImages/image6.jpg",
    company: "TAHVO",
    item_name: "Single-Breasted Two-Piece Suit",
    original_price: 8999,
    current_price: 4347,
    discount_percentage: 52,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.3,
      count: "9",
    },
  },
  {
    id: "007",
    image: "../Images/productImages/image7.jpg",
    company: "Campus Sutra",
    item_name: "Men Self Design Cotton T-shirt",
    original_price: 1699,
    current_price: 679,
    discount_percentage: 60,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.4,
      count: "18.7k",
    },
  },
  {
    id: "008",
    image: "../Images/productImages/image8.jpg",
    company: "Mast & Harbour",
    item_name: "Printed Oversized Sweatshirt",
    original_price: 1999,
    current_price: 545,
    discount_percentage: 73,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 3.2,
      count: "804",
    },
  },
  {
    id: "009",
    image: "../Images/productImages/image9.jpg",
    company: "HRX by Hrithik Roshan",
    item_name: "Rapid-Dry Sports Tracksuit",
    original_price: 4299,
    current_price: 1203,
    discount_percentage: 72,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 3.8,
      count: "1.6k",
    },
  },
  {
    id: "010",
    image: "../Images/productImages/image10.jpg",
    company: "Jompers",
    item_name: "Embroidered Kurta Set",
    original_price: 7099,
    current_price: 1774,
    discount_percentage: 75,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.0,
      count: "2.3k",
    },
  },
  {
    id: "011",
    image: "../Images/productImages/image11.jpg",
    company: "Nap Chief",
    item_name: "Kids Cotton Clothing Set",
    original_price: 1490,
    current_price: 850,
    discount_percentage: 43,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.6,
      count: "205",
    },
  },
  {
    id: "012",
    image: "../Images/productImages/image12.jpg",
    company: "Nap Chief",
    item_name: "Kids Cotton Cargo Joggers",
    original_price: 1390,
    current_price: 790,
    discount_percentage: 43,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.5,
      count: "1.3k",
    },
  },
  {
    id: "013",
    image: "../Images/productImages/image13.jpg",
    company: "Sangria",
    item_name: "Fit & Flared Maxi Dress",
    original_price: 2849,
    current_price: 1054,
    discount_percentage: 63,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.0,
      count: "14",
    },
  },
  {
    id: "014",
    image: "../Images/productImages/image14.jpg",
    company: "Nauti Nati",
    item_name: "Girls Printed Top with Shorts",
    original_price: 1499,
    current_price: 734,
    discount_percentage: 51,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.3,
      count: "5.2k",
    },
  },
  {
    id: "015",
    image: "../Images/productImages/image15.jpg",
    company: "Aj DEZInES",
    item_name: "Boys Pure Cotton Kurta",
    original_price: 1999,
    current_price: 499,
    discount_percentage: 75,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.2,
      count: "1.1k",
    },
  },
  {
    id: "016",
    image: "../Images/productImages/image16.jpg",
    company: "HRX by Hrithik Roshan",
    item_name: "Unisex Running Shoes",
    original_price: 2999,
    current_price: 898,
    discount_percentage: 70,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.3,
      count: "4.2k",
    },
  },
  {
    id: "017",
    image: "../Images/productImages/image17.jpg",
    company: "Aura",
    item_name: "Printed Decals & Sticker",
    original_price: 599,
    current_price: 167,
    discount_percentage: 72,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.4,
      count: "499",
    },
  },
  {
    id: "018",
    image: "../Images/productImages/image18.jpg",
    company: "LEGEND EYEWEAR",
    item_name: "Unisex Wayfarer Sunglasses",
    original_price: 1999,
    current_price: 373,
    discount_percentage: 81,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.5,
      count: "216",
    },
  },
  {
    id: "019",
    image: "../Images/productImages/image19.jpg",
    company: "Daniel Klein",
    item_name: "Men's Leather Analogue Watch",
    original_price: 6600,
    current_price: 2376,
    discount_percentage: 64,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.2,
      count: "15.7k",
    },
  },
  {
    id: "020",
    image: "../Images/productImages/image20.jpg",
    company: "boAt",
    item_name: "Airdopes 163 TWS Earbuds",
    original_price: 2490,
    current_price: 899,
    discount_percentage: 64,
    return_period: 14,
    delivery_date: "30 May 2026",
    rating: {
      stars: 4.1,
      count: "51.2k",
    },
  },
];